package cblaho.foodtracker.activities;

import android.app.ActionBar;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.util.TypedValue;
import android.view.View;
import android.widget.RelativeLayout;
import android.widget.TableLayout;
import android.widget.TableRow;
import android.widget.TextView;

import java.util.Map;

import cblaho.foodtracker.R;
import cblaho.foodtracker.data.Food;
import cblaho.foodtracker.data.Recipe;

/**
 * Displays a recipe.
 */
public class RecipeDisplayOne extends Activity {
    /**
     * Sets all layout fields to the information specified by the recipe object passed in.
     * @param savedInstanceState generated by Android OS
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recipe_display_one);
        Intent intent = getIntent();
        Recipe recipe = intent.getParcelableExtra("recipe");
        ActionBar ab = getActionBar();
        if(ab != null) {
            ab.setTitle(recipe.getName());
        }
        TextView name = (TextView) this.findViewById(R.id.recipe_display_one_name);
        name.setText(recipe.getName());
        TextView servings = (TextView) this.findViewById(R.id.recipe_display_one_servings);
        servings.setText(recipe.getQty().toString());
        TableLayout ingredients = (TableLayout) this.findViewById(R.id.recipe_display_one_ingredients);
        //Dynamically add lines to table layout.
        for(Food f : recipe.getIngredients()) {
            TableRow tr = new TableRow(this);
            TextView fname = new TextView(this);
            TextView funit = new TextView(this);
            TextView fqty = new TextView(this);
            fname.setText(f.getName());
            funit.setText(f.getConversion());
            fqty.setText((Integer.valueOf(f.getQty().intValue())).toString());
            fname.setTextSize(16);
            funit.setTextSize(16);
            fqty.setTextSize(16);
            fname.setPadding(0, 0, 20, 0);
            funit.setPadding(0,0,20,0);
            fqty.setPadding(0,0,20,0);
            tr.addView(fqty);
            tr.addView(funit);
            tr.addView(fname);
            TableRow.LayoutParams p = new TableRow.LayoutParams();
            p.rightMargin = 10;
            tr.setLayoutParams(p);
            ingredients.addView(tr);
        }
        TextView steps = (TextView) this.findViewById(R.id.recipe_display_one_steps);
        steps.setText(recipe.getSteps());

        View hBar;
        RelativeLayout.LayoutParams hParams = new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.MATCH_PARENT,
                (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 2, getResources().getDisplayMetrics())
        );

        TableLayout nutrients = (TableLayout) this.findViewById(R.id.recipe_display_one_nutrients);
        for(Map.Entry<String,Double> nutrient : recipe.getNutrients().entrySet()) {
            hBar = new View(this.getApplicationContext());
            hBar.setLayoutParams(hParams);
            hBar.setBackgroundColor(getResources().getColor(R.color.primary));
            TableRow tr = new TableRow(this);
            TextView nname = new TextView(this);
            TextView nqty = new TextView(this);
            nname.setText(nutrient.getKey());
            nqty.setText(nutrient.getValue().toString());
            nname.setTextSize(16);
            nqty.setTextSize(16);
            nname.setPadding(0,0,20,0);
            nqty.setPadding(0,0,20,0);
            tr.addView(nname);
            tr.addView(nqty);
            nutrients.addView(tr);
            nutrients.addView(hBar); //thin colored line to make things pretty
        }
    }

    /**
     * Onclick handler for the "Back To List" button on the recipe display layout.
     *
     * @param v Generated by Android OS
     */
    public void backToList(View v){
        Intent intent = new Intent(RecipeDisplayOne.this, RecipeList.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP); //don't add this to the activity stack
        startActivity(intent);
    }
}
