package cblaho.foodtracker.activities;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.TextView;

import cblaho.foodtracker.R;

/**
 * Created by cblaho on 9/2/15.
 * List adapter for search results
 */
public class SearchResultsAdapter extends ArrayAdapter<RecipePair> {
    public SearchResultsAdapter(Context context, int layoutResourceId, RecipePair[] data) {
        super(context, layoutResourceId, data);
    }

    /**
     * Adapter for the Search results List. Typical inflater.
     * @param position generated by Android OS
     * @param convertView generated by Android OS
     * @param parent generated by Android OS
     * @return view we have created
     */
    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        if(convertView == null) {
            LayoutInflater inflater = (LayoutInflater) this.getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(R.layout.search_results_row, parent, false);
        }

        TextView name = (TextView) convertView.findViewById(R.id.search_result_name);

        name.setText(this.getItem(position).getName());

        return convertView;
    }

}
